version: 2

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
    - GOPRIVATE=github.com/xdagiz/xytz
  mod: mod

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/xdagiz/xytz/internal/version.Version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "xytz-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  header: |
    # {{ .Version }}

    <!-- what's new in this version? -->

    To install run:
    ```bash
    # Binary download
    curl -sSL https://xdagiz.dev/xytz/install.sh | bash

    # Or via Go
    go install github.com/xdagiz/xytz@latest
    ```

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*\\(deps\\)*:+.*$"
      order: 300
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "Documentation updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999
